# -*- coding: utf-8 -*-
"""MDF_exemplo1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11QiY2AoV1k5PSVuFmyFhABiVc1zBN1vx

# Exemplo 1
Utilizando o Método das Diferenças Finitas, vamos resolver a seguinte equação diferencial:
$$
\begin{cases}
    \frac{\partial^2 u}{\partial x^2} + u + x = 0 \\
    u(0) = 0 \\
    u(1) = 1
\end{cases}
$$

Para isso, vamos usar um $\Delta x = 0.25$.

A fórmual de Diferença Finita para essa equação é dada por:

\begin{align}
u_{i+1} + [(\Delta x)^2 -2]u_i + u_{i-1} = -(\Delta x)^2 x_i
\end{align}
"""

#importação das bibliotecas

import numpy as np
import matplotlib.pyplot as plt

#Parâmetros do Problema

L = 1         #domínio
n = 4         #número de intervalos
dx = L/n      #tamanho do passo
print(dx)

#Condições de Contorno
u_0 = 0       #condição de contorno em x = 0
u_final = 1   #condição de contorno em x = L

"""Perceba que no caso desse problema, cada ponto depende um do outro, ou seja, as equações estão acopladas e o esquema de Diferenças Finitas é chamado Implícito. É por isso que exige que a solução seja encontrada via sistema de equações."""

#Construindo as matrizes

n_incog = n-1                     #dado que temos as condições de contorno e temos sempre n + 1 pontos, o número de pontos desconhecidos é (n + 1) - 2 = n-1
A = np.zeros((n_incog, n_incog))
b = np.zeros(n_incog)

#Já que transformamos nossa equação de diferença finitas na equação Ax = b, vamos montar a matriz A e o vetor b

for i in range(n_incog):
  xi = (i + 1)*dx          #valor de xi no índice i

  A[i,i] = (dx**2) - 2     #preenchendo a diagonal principal

  if i > 0:                #preenchendo a primeira diagonal à esquerda
    A[i, i-1] = 1

  if i < (n-2):            #preenchendo a primeira diagonal à direita
    A[i, i+1] = 1

  b[i] = -(dx**2)*xi       #vetor b

  #ajuste nas Condições de Contorno
  b[0] = b[0] - u_0
  b[-1] = b[-1] - u_final

print("Matriz A =", A)
print("Vetor b =", b)

#Solução do sistema de equações

sol = np.linalg.solve(A, b)     #a função linalg.solve resolve o sistema de equações
print("Solução =", sol)

#Solução Analítica

def u(x):
  return 2*np.sin(x)/np.sin(1) - x

sol_analitica = []

for i in range (n_incog):
  xi = (i + 1)*dx
  valor = u(xi)
  sol_analitica.append(valor)
  print(f"u({xi}) =", valor)

#Diferença entre a solução analítica e a solução numérica

erro = sol_analitica - sol
erro

